ALTER TABLE log_entry
    ALTER COLUMN message TYPE VARCHAR(255),
    ALTER COLUMN ip TYPE VARCHAR(15),
    ALTER COLUMN user_agent TYPE VARCHAR(255),
    ALTER COLUMN extra_info TYPE VARCHAR(255);


ALTER TABLE incident
    ALTER COLUMN details TYPE VARCHAR(255);

ALTER TABLE exception_log
    ALTER COLUMN message TYPE VARCHAR(255);
